# Generated by Django 3.0.4 on 2020-04-18 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200417_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='mp3',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
