# Generated by Django 3.0.4 on 2020-04-18 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_mp3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='mp3',
        ),
        migrations.AddField(
            model_name='song',
            name='mp3',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/'),
            preserve_default=False,
        ),
    ]
